# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContinuewatchingContentIdBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, last_watched_minute: int=None):  # noqa: E501
        """ContinuewatchingContentIdBody1 - a model defined in Swagger

        :param last_watched_minute: The last_watched_minute of this ContinuewatchingContentIdBody1.  # noqa: E501
        :type last_watched_minute: int
        """
        self.swagger_types = {
            'last_watched_minute': int
        }

        self.attribute_map = {
            'last_watched_minute': 'last_watched_minute'
        }
        self._last_watched_minute = last_watched_minute

    @classmethod
    def from_dict(cls, dikt) -> 'ContinuewatchingContentIdBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The continuewatching_content_id_body_1 of this ContinuewatchingContentIdBody1.  # noqa: E501
        :rtype: ContinuewatchingContentIdBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def last_watched_minute(self) -> int:
        """Gets the last_watched_minute of this ContinuewatchingContentIdBody1.

        The minute where the user stopped watching  # noqa: E501

        :return: The last_watched_minute of this ContinuewatchingContentIdBody1.
        :rtype: int
        """
        return self._last_watched_minute

    @last_watched_minute.setter
    def last_watched_minute(self, last_watched_minute: int):
        """Sets the last_watched_minute of this ContinuewatchingContentIdBody1.

        The minute where the user stopped watching  # noqa: E501

        :param last_watched_minute: The last_watched_minute of this ContinuewatchingContentIdBody1.
        :type last_watched_minute: int
        """
        if last_watched_minute is None:
            raise ValueError("Invalid value for `last_watched_minute`, must not be `None`")  # noqa: E501

        self._last_watched_minute = last_watched_minute
