# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, languages: List[str]=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param languages: The languages of this InlineResponse2005.  # noqa: E501
        :type languages: List[str]
        """
        self.swagger_types = {
            'languages': List[str]
        }

        self.attribute_map = {
            'languages': 'languages'
        }
        self._languages = languages

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def languages(self) -> List[str]:
        """Gets the languages of this InlineResponse2005.


        :return: The languages of this InlineResponse2005.
        :rtype: List[str]
        """
        return self._languages

    @languages.setter
    def languages(self, languages: List[str]):
        """Sets the languages of this InlineResponse2005.


        :param languages: The languages of this InlineResponse2005.
        :type languages: List[str]
        """

        self._languages = languages
