# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, content_id: int=None, rating: int=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param user_id: The user_id of this InlineResponse2002.  # noqa: E501
        :type user_id: int
        :param content_id: The content_id of this InlineResponse2002.  # noqa: E501
        :type content_id: int
        :param rating: The rating of this InlineResponse2002.  # noqa: E501
        :type rating: int
        """
        self.swagger_types = {
            'user_id': int,
            'content_id': int,
            'rating': int
        }

        self.attribute_map = {
            'user_id': 'userId',
            'content_id': 'contentId',
            'rating': 'rating'
        }
        self._user_id = user_id
        self._content_id = content_id
        self._rating = rating

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this InlineResponse2002.

        The ID of the user who wrote the review  # noqa: E501

        :return: The user_id of this InlineResponse2002.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this InlineResponse2002.

        The ID of the user who wrote the review  # noqa: E501

        :param user_id: The user_id of this InlineResponse2002.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def content_id(self) -> int:
        """Gets the content_id of this InlineResponse2002.

        The ID of the content being reviewed  # noqa: E501

        :return: The content_id of this InlineResponse2002.
        :rtype: int
        """
        return self._content_id

    @content_id.setter
    def content_id(self, content_id: int):
        """Sets the content_id of this InlineResponse2002.

        The ID of the content being reviewed  # noqa: E501

        :param content_id: The content_id of this InlineResponse2002.
        :type content_id: int
        """

        self._content_id = content_id

    @property
    def rating(self) -> int:
        """Gets the rating of this InlineResponse2002.

        User's rating for the content (1 to 5 stars)  # noqa: E501

        :return: The rating of this InlineResponse2002.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this InlineResponse2002.

        User's rating for the content (1 to 5 stars)  # noqa: E501

        :param rating: The rating of this InlineResponse2002.
        :type rating: int
        """

        self._rating = rating
