# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002Recommendations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, content_id: int=None, title: str=None):  # noqa: E501
        """InlineResponse2002Recommendations - a model defined in Swagger

        :param content_id: The content_id of this InlineResponse2002Recommendations.  # noqa: E501
        :type content_id: int
        :param title: The title of this InlineResponse2002Recommendations.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'content_id': int,
            'title': str
        }

        self.attribute_map = {
            'content_id': 'content_id',
            'title': 'title'
        }
        self._content_id = content_id
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002Recommendations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2_recommendations of this InlineResponse2002Recommendations.  # noqa: E501
        :rtype: InlineResponse2002Recommendations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content_id(self) -> int:
        """Gets the content_id of this InlineResponse2002Recommendations.

        The ID of the recommended content  # noqa: E501

        :return: The content_id of this InlineResponse2002Recommendations.
        :rtype: int
        """
        return self._content_id

    @content_id.setter
    def content_id(self, content_id: int):
        """Sets the content_id of this InlineResponse2002Recommendations.

        The ID of the recommended content  # noqa: E501

        :param content_id: The content_id of this InlineResponse2002Recommendations.
        :type content_id: int
        """

        self._content_id = content_id

    @property
    def title(self) -> str:
        """Gets the title of this InlineResponse2002Recommendations.

        Title of the recommended content  # noqa: E501

        :return: The title of this InlineResponse2002Recommendations.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this InlineResponse2002Recommendations.

        Title of the recommended content  # noqa: E501

        :param title: The title of this InlineResponse2002Recommendations.
        :type title: str
        """

        self._title = title
