# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2002_recommendations import InlineResponse2002Recommendations  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, recommendations: List[InlineResponse2002Recommendations]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param recommendations: The recommendations of this InlineResponse2002.  # noqa: E501
        :type recommendations: List[InlineResponse2002Recommendations]
        """
        self.swagger_types = {
            'recommendations': List[InlineResponse2002Recommendations]
        }

        self.attribute_map = {
            'recommendations': 'recommendations'
        }
        self._recommendations = recommendations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recommendations(self) -> List[InlineResponse2002Recommendations]:
        """Gets the recommendations of this InlineResponse2002.


        :return: The recommendations of this InlineResponse2002.
        :rtype: List[InlineResponse2002Recommendations]
        """
        return self._recommendations

    @recommendations.setter
    def recommendations(self, recommendations: List[InlineResponse2002Recommendations]):
        """Sets the recommendations of this InlineResponse2002.


        :param recommendations: The recommendations of this InlineResponse2002.
        :type recommendations: List[InlineResponse2002Recommendations]
        """

        self._recommendations = recommendations
