# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reviews: List[object]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param reviews: The reviews of this InlineResponse2001.  # noqa: E501
        :type reviews: List[object]
        """
        self.swagger_types = {
            'reviews': List[object]
        }

        self.attribute_map = {
            'reviews': 'reviews'
        }
        self._reviews = reviews

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reviews(self) -> List[object]:
        """Gets the reviews of this InlineResponse2001.


        :return: The reviews of this InlineResponse2001.
        :rtype: List[object]
        """
        return self._reviews

    @reviews.setter
    def reviews(self, reviews: List[object]):
        """Sets the reviews of this InlineResponse2001.


        :param reviews: The reviews of this InlineResponse2001.
        :type reviews: List[object]
        """

        self._reviews = reviews
