# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UsersUserIdBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rating: int=None):  # noqa: E501
        """UsersUserIdBody1 - a model defined in Swagger

        :param rating: The rating of this UsersUserIdBody1.  # noqa: E501
        :type rating: int
        """
        self.swagger_types = {
            'rating': int
        }

        self.attribute_map = {
            'rating': 'rating'
        }
        self._rating = rating

    @classmethod
    def from_dict(cls, dikt) -> 'UsersUserIdBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The users_userId_body_1 of this UsersUserIdBody1.  # noqa: E501
        :rtype: UsersUserIdBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rating(self) -> int:
        """Gets the rating of this UsersUserIdBody1.

        Rating for the content (1 to 5 stars)  # noqa: E501

        :return: The rating of this UsersUserIdBody1.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this UsersUserIdBody1.

        Rating for the content (1 to 5 stars)  # noqa: E501

        :param rating: The rating of this UsersUserIdBody1.
        :type rating: int
        """

        self._rating = rating
