# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ViewRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, view_count: int=None):  # noqa: E501
        """ViewRequest - a model defined in Swagger

        :param view_count: The view_count of this ViewRequest.  # noqa: E501
        :type view_count: int
        """
        self.swagger_types = {
            'view_count': int
        }

        self.attribute_map = {
            'view_count': 'view_count'
        }
        self._view_count = view_count

    @classmethod
    def from_dict(cls, dikt) -> 'ViewRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ViewRequest of this ViewRequest.  # noqa: E501
        :rtype: ViewRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def view_count(self) -> int:
        """Gets the view_count of this ViewRequest.

        The number of views to add  # noqa: E501

        :return: The view_count of this ViewRequest.
        :rtype: int
        """
        return self._view_count

    @view_count.setter
    def view_count(self, view_count: int):
        """Sets the view_count of this ViewRequest.

        The number of views to add  # noqa: E501

        :param view_count: The view_count of this ViewRequest.
        :type view_count: int
        """
        if view_count is None:
            raise ValueError("Invalid value for `view_count`, must not be `None`")  # noqa: E501

        self._view_count = view_count
